// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystdlhflttjkaozwukmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdGRsaGZsdHRqa2Fvend1a21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzQwNzQsImV4cCI6MjA3MDE1MDA3NH0.1bRFWdN3VLYqlW62bz-9yNCGPDOWm__hwWQmbdoWCdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});